### PR TITLE
#123: fix lib naming

### PR DESCRIPTION
**Pull request by flagos**
Proposition to make the UI selection of biblitheque folder work. Please note that the UI is not refreshed after selection but it seems it was already like that.

### CODE REVIEW

**Comment by 314r** [comment]
Thanks !

**Comment by flagos** [comment]
Hi, 

Any update on this PR and on the others ?

Cheers,

**Comment by 314r** [comment]
I'm back and should be able to find some time to release a new version of joliebulle this summer, focused on bugfixes.

**Comment by 314r** [comment]
Thanks a lot for your work and your PRs.

**Pull request merged**
